final juicyTerms = [
  "dev",
  "dev1",
  "dev2",
  "dev3",
  "development",
  "test",
  "testing",
  "qa",
  "staging",
  "hml",
  "sandbox",
  "demo",
  "preview",
  "beta",
  "alpha",
  "preprod",
  "uat",
  "jenkins",
  "git",
  "gitlab",
  "bitbucket",
  "ci",
  "cicd",
  "pipeline",
  "artifactory",
  "nexus",
  "registry",
  "docker",
  "harbor",
  "login",
  "signin",
  "auth",
  "authentication",
  "sso",
  "saml",
  "oauth",
  "register",
  "signup",
  "password",
  "reset",
  "forgot",
  "token",
  "vpn",
  "remote",
  "access",
  "gateway",
  "firewall",
  "admin",
  "adminpanel",
  "manage",
  "dashboard",
  "console",
  "cms",
  "intranet",
  "internal",
  "private",
  "secure",
  "portal",
  "support",
  "help",
  "helpdesk",
  "it",
  "ticket",
  "jira",
  "confluence",
  "servicenow",
  "db",
  "database",
  "mysql",
  "postgres",
  "mongo",
  "sql",
  "redis",
  "api",
  "backend",
  "tools",
  "monitoring",
  "status",
  "uptime",
  "metrics",
  "grafana",
  "prometheus",
  "logs",
  "log",
  "kibana",
  "elastic",
  "public",
  "static",
  "files",
  "uploads",
  "content",
  "assets",
  "media",
  "old",
  "backup",
  "bak",
  "temp",
  "tmp",
  "archive",
];

// Casa cada termo apenas quando isolado como label de subdomínio, ou seja,
// delimitado por não-alfanuméricos (`.`, `-`, `/`, `:`, início/fim). Evita
// falsos positivos por substring — "api" não casa "rapidshare", "old" não
// casa "gold", "ci" não casa "social".
final juicyRegex = RegExp(
  '(?<![a-zA-Z0-9])(?:${juicyTerms.map(RegExp.escape).join('|')})(?![a-zA-Z0-9])',
  caseSensitive: false,
);

List<String> identifyJuicyTargets(List<String> urls) {
  return urls.where((url) => juicyRegex.hasMatch(url)).toList();
}
